## courtesy of https://academicpages.github.io/

# Basic Site Settings
title: Vinit Shah
logo: ./docs/assets/images/1712083718457.jpeg
description: Machine Learning, Digital Signal Processing
locale                   : "en-US"
title_separator          : "-"
name                     : &name "Vinit Shah"
description              : &description "Time-Series Analysis Enthusiast"
url                      : https://Wiinvin.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Wiinvin.github.io/Wiinvin"

theme: jekyll-theme-minimal

